version: '2.0'

services:

  postgres:
    image: postgres:12-alpine
    environment:
      POSTGRES_USER: username
      POSTGRES_PASSWORD: password
    ports:
      - 5432:5432
    volumes:
      - ${PWD}/postgresql:/docker-entrypoint-initdb.d
