version: '2.0'

services:

  web:
    build:
      context: .
    environment:
      DATABASE: 'postgres://username:password@postgres'
    ports:
      - 8080:80

  postgres:
    build:
      context: postgresql
    environment:
      POSTGRES_USER: username
      POSTGRES_PASSWORD: password
    ports:
      - 5432:5432
